; PlatformIO Project Configuration File
;
;   Build:  pio run
;   Upload: pio run -t upload
;   Monitor: pio device monitor

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

lib_deps =
    bogde/HX711@^0.7.5

monitor_speed = 115200
upload_speed = 921600
